/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ghost.gltf --transform
Author: Elite 3D (https://sketchfab.com/Elite3DModelling)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/ghost-face-classic-game-model-2981fc301db041728fd28c8918c81086
Title: Ghost Face Classic Game Model
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/ghost-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.OK_Mask006_REF001_MI_OKMask_0.geometry} material={materials.MI_OKMask} position={[0, 164.52, 12.3]} />
        <mesh geometry={nodes.OK_Body007_REF001_MI_OKHead007_0.geometry} material={materials.MI_OKHead007} />
        <mesh geometry={nodes.OK_Body007_REF001_MI_OKHood007_0.geometry} material={materials.MI_OKHood007} />
        <mesh geometry={nodes.OK_Body007_REF001_MI_OKLegs007_0.geometry} material={materials.MI_OKLegs007} />
        <mesh geometry={nodes.OK_Body007_REF001_MI_OKTorso007_0.geometry} material={materials.MI_OKTorso007} />
        <mesh geometry={nodes.OK_Body007_REF001_MI_OKDress007_0.geometry} material={materials.MI_OKDress007} />
      </group>
    </group>
  )
}

useGLTF.preload('/ghost-transformed.glb')
